-- CREAR LA BASE DE DATOS
CREATE DATABASE clientes;

-- SELECCIONAR LA BASE DE DATOS 
USE clientes;
-- MOSTRAR BASES DE DATOS DEL SERVIDOR
SHOW DATABASES;
-- CREACION DE LA TABLA CLIENTES
CREATE TABLE clientes(
		id_cliente INT (10),
		nombre TEXT(15) NOT NULL,
		correo TEXT(100) NOT NULL,
		contraseña TEXT(255) NOT NULL,
		fecha_registro DATE(50) NOT NULL,
		genero VARCHAR(10) NOT NULL,
		PRIMARY KEY(id_cliente)
);